# Generated by Django 4.1.2 on 2022-10-04 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InstantCart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="items",),
        migrations.AddField(
            model_name="orders",
            name="products",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), default=[], size=None
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="quantities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), default=[], size=None
            ),
        ),
    ]
