# Generated by Django 4.1.2 on 2022-11-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('product_id', models.CharField(default='', max_length=255)),
                ('upc', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default=0)),
                ('expiration', models.DateField(null=True)),
                ('comments', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
