# Generated by Django 4.0.4 on 2022-10-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='add_to_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='expiration',
            field=models.DateField(null=True),
        ),
    ]
