# Generated by Django 4.1.2 on 2022-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='add_to_list',
        ),
        migrations.RemoveField(
            model_name='pantry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='pantry',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pantry',
            name='product_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pantry',
            name='upc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='comments',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pantry',
            name='expiration',
            field=models.DateField(null=True),
        ),
    ]
