# Generated by Django 4.0.4 on 2022-09-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
        ('pantry', '0002_pantry_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantry',
            name='comments',
        ),
        migrations.AddField(
            model_name='pantry',
            name='add_to_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.shoppinglist'),
            preserve_default=False,
        ),
    ]
