# Generated by Django 4.0.4 on 2022-09-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_pantry_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantry',
            name='add_to_list',
            field=models.CharField(max_length=255),
        ),
    ]
