# Generated by Django 4.0.4 on 2022-09-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_alter_pantry_add_to_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
