# Generated by Django 4.0.4 on 2022-09-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('pantry', '0007_remove_pantry_add_to_list_remove_pantry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='add_to_list',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pantry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pantry',
            name='comments',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pantry',
            name='expiration',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
