# Generated by Django 4.1.2 on 2022-10-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0002_cart_shoppinglist_quantity_alter_shoppinglist_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='total',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
